services:
  # Semi-proprietary module enclave
  semiprop-enclave:
    build:
      context: .
      dockerfile: enclave/Dockerfile
    container_name: semiprop-sudoku-enclave
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mount bulletin board for persistence
      - ./bulletin_board:/app/bulletin_board:rw
    restart: unless-stopped

    # Security configurations for enclave simulation
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/node_modules/.cache
      - /app/test_temp:uid=1001,gid=1001

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s